### ISSUE TITLE
Syntax highlighting issue when there is no space preceding <

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/TypeScript-TmLanguage#11]
Ported from https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/285

Related to https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/265.

Issue:
![image](https://cloud.githubusercontent.com/assets/1707813/8627292/da8f8be4-26fe-11e5-97ce-2b2a8b257afa.png)

Correct:
![image](https://cloud.githubusercontent.com/assets/1707813/8627340/3e27dbf2-26ff-11e5-8751-7e8576cbd230.png)

**Comment by leozzyzheng** [comment]
Have this solved on vscode ?

**Comment by Tyriar** [comment]
I don't have enough experience with text grammars to be able to come up with a solution to this problem, but here are some of my notes.

Here is the problem:

```
           From here to the end of the line is matched with
           type-parameters, the rule for generics (foo<T>)
               |
               v
for (var i=0; i<10; i++) {
```

This issue is caused by the `type-parameters` key, the grammar thinks a generic is in the for loop despite it never matching a `>`. Matching of generics stops at the end of the line because of this:

```xml
<key>type-parameters</key>
<dict>
    ...
    <key>end</key>
    <string>(?=$)|(&gt;)</string>
```

The above is saying the end of `type-parameters` is either the end of the line or a `>` symbol. It seems what this should be, at least to resolve the current issue with `for` loops without improving upon single-line only generics is to only match `type-parameters` when `>` is on the same line after the matching `<`, otherwise don't match. I don't know if forcing begin-end groups to only work on a single line is possible though.

**Comment by alexandrudima** [comment]
This brings a major hit for minified JavaScript that causes VSCode to crash with trivial ammounts of JS code (80K). The grammar ends up pushing 48 states because of the type-parameters rule. Please see Microsoft/vscode#6916 where we crash with a minified line of JS that contains `<` as a comparison operator.

**Comment by alexandrudima** [comment]
@zhengbli 

Assuming you're ok with at most 3 levels of generics you can fix this simply by turning your begin/end rule into a match rule with a regexp like:

```
<([a-zA-Z_$][\w$]*)(\.([a-zA-Z_$][\w$]*))*(<([a-zA-Z_$][\w$]*)(\.([a-zA-Z_$][\w$]*))*(<([a-zA-Z_$][\w$]*)(\.([a-zA-Z_$][\w$]*))*>)?>)?>
```

Of course you can go to 4 if you want, the rule is the following:
* assume we have `Identifier` = `([a-zA-Z_$][\w$]*)`
* assume you have `Type` = `Identifier(.Identifier)*`
* the rule above is: `<Type(<Type(<Type>)?>)?>`
* it is easy to extend to 4 levels if you see that sort of code in the wild.

![image](https://cloud.githubusercontent.com/assets/5047891/15576407/ffc262d2-2357-11e6-9e5a-223c4cc2a79f.png)

You can then refine the `match` by reparsing the text if you wanna produce different tokens:

See here an example:
https://github.com/Microsoft/vscode-textmate/blob/master/test-cases/first-mate/fixtures/makefile.json#L350

Here the match is further (re)tokenized to assign more fine-grained tokens.
![image](https://cloud.githubusercontent.com/assets/5047891/15576512/9401cf46-2358-11e6-9a87-f551f1fc4d5a.png)

**Comment by alexandrudima** [comment]
Ok, @aeschli pointed out that there might be commas in there, so I've just learned about `\g` that appears to be supported in oniguruma:

`(<([\w\.\,\ ]+|\g<1>)*>)`

https://regex101.com/r/kX9gH4/1

![image](https://cloud.githubusercontent.com/assets/5047891/15579387/b99c5832-2364-11e6-8b61-4b38a5042542.png)

**Comment by zhengbli** [comment]
Got some time to work on this now. Heads up: the type parameter may not be like `Identifier.Identifier`, it could be the following as well:
- `(param?: number) => void` 
- `A | B`
- `A & B`
- `T extends {a: () => string}`

**Comment by sheetalkamat** [comment]
191f6c2  should fix this
