### ISSUE TITLE
"latest TypeScript grammar" broken

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/TypeScript-TmLanguage#274]
Installed https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar (with Dark+):

![image](https://cloud.githubusercontent.com/assets/10532611/18948107/0e1ad88c-8636-11e6-9d5d-3fd36dabeaa3.png)

I'm not sure how it _should_ be, but it doesn't seem right.
 - Previously, green was only for classes and interfaces, not it is for properties aswell. 
 - keywords like `await` or `delete` are not colored
 - object access is sometimes white, sometimes light blue
 - `require()` is violet

Code:
```ts
import fetch from 'node-fetch';
import * as assert from 'assert';
import {API_URL} from '../../../../api/../config';
import {createTestToken, shouldRequireAdminPermission} from '../helper';
import {Product} from '../../../../api/models/investment/Product';
import {Notification} from '../../../../api/models/core/Notification';
import Sequelize = require('sequelize');
import * as sinon from 'sinon';
import {pusher} from '../../../../api/pusher';
import {assertDeepEqual} from '../helper';
import {pick, omit} from 'lodash';

describe('Product', () => {
    describe('GET /products', () => {
        shouldRequireAdminPermission('GET', '/products');
        it('should return a list of products', async () => {
            const product = await Product.create({
                name: 'Goldmine SMSF',
                description: 'Established goldmine self-managed super fund',
                type: 'unit',
                status: 'open',
                distributionPeriod: 'annually',
                distributionDate: new Date(Date.UTC(2016, 8, 7)),
                startDate: new Date(Date.UTC(2016, 8, 5)),
                endDate: new Date(Date.UTC(2016, 9, 5)),
                couponRate: '0.05',
                termType: 'absolute',
                managerId: 1
            });
            const token = createTestToken({ permissions: ['admin'] });
            const res = await fetch(API_URL + '/products', { headers: { 'Authorization': 'Bearer ' + token } });
            assert.equal(res.status, 200);
            const body = await res.json();
            delete body[0].createdAt;
            delete body[0].updatedAt;
            assert.equal(~~res.headers.get('x-total-count'), 1);
            assertDeepEqual(body, [{
                id: product.id,
```

**Comment by sheetalkamat** [comment]
@felixfbecker await not being colored is bug in the grammar and I have fix for it. Thanks for reporting it.
I also have a fix for object literal keys colored green. 

```delete``` is ```keyword.operator.delete``` and it should be colored like keyword and dark+ theme doesn't do that. I will report it in vscode repo

object accesses like assert are scoped as support objects and dark theme doesn't color it. Eg. look at function call ```res.headers.get``` the get is not colored as it is classified as support.function which should be colored as atleast other functions are colored. I am filing bug in vscode for this so they can make changes in their theme.

require is violet by design just like import and from in other import statements. It is control keyword that makes import and external import and hence the color.

**Comment by felixfbecker** [comment]
Thanks for looking into this, but I disagree with the last statement. `require` is nothing but a global function.

**Comment by sheetalkamat** [comment]
@felixfbecker From typescript perspective require is a special keyword that determines what the lhs import variable means and hence the control keyword
