### ISSUE TITLE
Regex highlighting inside arrow function expressions

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#297]
_From @massimocode on September 22, 2016 8:17_

- VSCode Version: Version 1.6.0-insider
- OS Version: Windows 10 x64 with Anniversary Update

See image below, regex is not highlighted as expected:
![image](https://cloud.githubusercontent.com/assets/3898363/18741105/44c788d0-80a5-11e6-8f31-5426bd59c67e.png)

_Copied from original issue: Microsoft/vscode#12429_

**Comment by sheetalkamat** [comment]
@massimocode  This should be fixed in the grammar by #257 
It is available via [vscode extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar)

![colors](https://cloud.githubusercontent.com/assets/8052792/19245379/a18acf94-8ed5-11e6-8421-8eb58f2b0213.JPG)
