### ISSUE TITLE
Multi-line destructuring breaks keyword highlighting

### ISSUE THREAD

**Issue by wattsbn** [Microsoft/TypeScript-TmLanguage#331]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.4 / latest

Notice that the last `this` in the screenshot is not highlighted. Note that I tried using the beta version by installing the vscode plugin and it was worse. The beta version did not highlight any of `this` keywords regardless of whether destructuring is present.

**Code**

```
class ExampleClass {
    private myVariable: any;

    constructor(params: any) {
        this.myVariable = 5;

        let { example } = params;
        this.myVariable = example;

        let {
            anotherExample
        } = params;
        this.myVariable = anotherExample;
    }
}
```
![image](https://cloud.githubusercontent.com/assets/850664/19707513/df2b4b5a-9acc-11e6-8813-480a3e3e093d.png)

**Comment by sheetalkamat** [comment]
This is fixed by latest grammar and is below is screen shot with [TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version: 0.0.6

![capture](https://cloud.githubusercontent.com/assets/8052792/19707880/6ba6aae6-9acf-11e6-9054-eae99cc30474.JPG)

Note that the screen shot is in VSCode insider build as VSCode currently has issue: Microsoft/vscode#13044 because of which ```this``` is not colored correctly.
