### ISSUE TITLE
Javascript syntax highliting issue

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/TypeScript-TmLanguage#360]
_From @iMasoud on November 17, 2016 12:38_

- VSCode Version: 1.7.1
- OS Version: linuxMint KDE 18

Steps to Reproduce:

1. create new js file in vscode
2. paste attached js code in that file

![screenshot_ _](https://cloud.githubusercontent.com/assets/9999208/20389749/7d3a5690-ace0-11e6-9f4d-6321139eb4dc.png)

Attention to url property of message_intity which has different color than it's siblings.

[mongoose.txt](https://github.com/Microsoft/vscode/files/597331/mongoose.txt)

_Copied from original issue: Microsoft/vscode#15639_

**Comment by sheetalkamat** [comment]
@ramya-rao-a / @iMasoud please post the code so we can investigate this,

**Comment by ramya-rao-a** [comment]
@sheetalkamat The code is attached as a text file in the comment above

**Comment by sheetalkamat** [comment]
We have safety net that stops guessing and applying rules on the end of the line. This means there is no way to distinguish if the ```{``` of the ```telegram_types_schema = 
{``` is object literal declaration or just the block. Since this is assumed as block, the url you are seeing colored differently is because it is support variable from node module. 

With the limitation of the textmate grammar, we wont be able to fix this. 

However there is work around for it by writing it as ```telegram_types_schema = {```
