### ISSUE TITLE
Function calls are not properly highlighted when adding a line-break between the function name and parentheses

### ISSUE THREAD

**Issue by zgredzik** [Microsoft/TypeScript-TmLanguage#438]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.18 / latest

**Code**

```ts
function foo(a:number, b:number) {
    return [a,b]
}

foo(1,2) // highlighted properly
foo // not highlighted
(1,2)
```
![image](https://cloud.githubusercontent.com/assets/2098250/24606248/9eabad5e-186c-11e7-9500-4939cb5efd6e.png)

The second use of `foo` is a correct function call from javascript perspective, but it's not highlighted as such. Highlighting those calls would help catch potentially incorrect function calls (missing / intentionally omitting semicolons in the preceding line yet for some reason starting the new line with `(`) as well as properly highlight function calls when using the "comma-first" style, as in:

```ts
const obj =
    { a : 1
    , b : 2
    }
const results = Object.keys(obj).reduce
    ( ( acc , key ) => { ... }
    , [] : SomeType
    )
```

**Comment by sheetalkamat** [comment]
This is by design and limitation of tmLanguage syntax. The regular expression usage to determine the syntax is never going to be completely correct because of the error recovery and lookup of one line at a time. This is the best we can do using tmLanguage syntax. Other grammars as well have same limitation, eg. try copying same code into sublime as js file and it would result in same coloring
