### ISSUE TITLE
type definition without semicolon breaks hl

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript-TmLanguage#440]
Incorrect hl:
```ts
type Type = 'some'

console.log('something')
```

Correct:
```ts
type Type = 'some'; // semi-colon

console.log('something')
```

**Comment by sheetalkamat** [comment]
This is by design due to limitation of tmLanguage grammar syntax wherein we can look up one line at a time. So its hard to do error recovery especially with just regular expressions. 
We allow type declaration to end only with another declaration or semicolon for colorization purposes as that's the most common scenario. 
If we treated new line as the end of type declaration there are many scenarios that would break like #166, #206
