### ISSUE TITLE
arrow function params in different lines

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript-TmLanguage#446]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.18 / latest

**Code**

```ts
// Please include a code snippet that demonstrates the issue
const addPackageToLockfile = (
  packages: { name: string, version: string, file?: boolean }[],
  options: { workingDir: string }) => {
```

**Comment by sheetalkamat** [comment]
This is by design and limitation of tm language syntax. The lookup for regex is only a line at a time so there is no easy way for error recovery and finding out surely if this is going to be arrow function when => is not on same line.

**Comment by whitecolor** [comment]
> so there is no easy way for error recovery and finding out surely if this is going to be arrow

should be hard way anyway?

**Comment by sheetalkamat** [comment]
> >so there is no easy way for error recovery and finding out surely if this is going to be arrow
> 
> then should be hard way anyway?
> 

No.. Because of new lines and single line lookup the simple scenarios are known to break the grammar. 
So we have to choose which cases would get better results.
eg. in your case on the line of ```const declaration``` we cant tell if ```(``` is arrow function or just normal parenthesized expression because we cant look up the next lines to see if there is arrow present or not.

**Comment by whitecolor** [comment]
> in your case on the line of const declaration we cant tell if ( is arrow function or just normal parenthesized expression because we cant look up the next lines to see if there is arrow present or not.

So why not handle this special case so that if parser see this case it would got thougth next lines? 

> The lookup for regex is only a line at a time

I understand this, but what makes it hard/impossible to add more needed flexibility to grammar parser? I don't think that handling special cases would make slower.

**Comment by sheetalkamat** [comment]
Because there is no easy way to recognize package is arrow parameter till you see arrow operator on next line. The tokenizing of any line works only a line at a time, which means by the time we see => operator its too late to categorize packages as arrow parameter.
Also there is distinguishing between parenthesized expression or arrow that needs to happen and cannot be surely tokenized with arrow until we see line 3 where => operator is present.

**Comment by whitecolor** [comment]
> The tokenizing of any line works only a line at a time, which means by the time we see => operator its too late to categorize packages as arrow parameter.

Why can this not be changed? And if => operator is met in such position than tokenizing could be redone for a certain number of previous lines (from the line where arrow function actually begins).

**Comment by sheetalkamat** [comment]
That's not how tmLanguage parsers work. They deal with one line at a time and there is no backtracking. Please see https://manual.macromates.com/en/language_grammars

**Comment by whitecolor** [comment]
> That's not how tmLanguage parsers work.

Then it is tm has a limited approach. Can't it be changed/upgraded?

**Comment by whitecolor** [comment]
There are actually is a lot of cases that can not be properly parsed due to this limitations, I think it is worth to reconsider the whole approach, it is really to limited `one line at a time`.

**Comment by whitecolor** [comment]
@mhegazy what do you think about it (more sophisticated syntax highlighting for TS) than just with line by line parser?
