### ISSUE TITLE
Text color problem

### ISSUE THREAD

**Issue by ugurozturk** [Microsoft/TypeScript-TmLanguage#447]
I'm using VS Code 1.11.2 and there is some color problem. Tested more than 4 theme but all failed. 

Lets see what i mean : 
![0](https://cloud.githubusercontent.com/assets/7994408/25362211/53c74c44-295b-11e7-9460-4d56d3d3ffe8.PNG)
As you see the "Geolocation" is different than others.

But actually they are same
![2](https://cloud.githubusercontent.com/assets/7994408/25362241/783f832a-295b-11e7-872a-8317f5890dde.PNG)
![3](https://cloud.githubusercontent.com/assets/7994408/25362243/79fa4b28-295b-11e7-94b8-0c152bee0568.PNG)
![4](https://cloud.githubusercontent.com/assets/7994408/25362246/7d647e82-295b-11e7-832b-4ac62a9f2260.PNG)

Tried to find what is the problem is and renamed my "Geolocation" func name and tried go to definition. Then it is just jumped to 
Microsoft VSCode\resources\app\extensions\node_modules\typescript\lib\lib.dom.d.ts
![1](https://cloud.githubusercontent.com/assets/7994408/25362297/b92e637e-295b-11e7-8472-28f8f485efcb.PNG)

**Comment by sheetalkamat** [comment]
@ugurozturk Please copy paste the code for easier investigation. From what I see, I think this is by design.
I see that the first screen shot is usage of ```Geolocation``` and it is recognized by js libraries as dom class and hence the color green. Note that declarations then be it variable/import they will be classified as variables and hence blue and class names in declaration are always green. Since this is just the regular expression scanner which doesn't have semantic info this is best we can do.

**Comment by ugurozturk** [comment]
@sheetalkamat 
Fixed : *.\Microsoft VS Code\resources\app\extensions\typescript\syntaxes\TypeScript.tmLanguage.json

Removed to "Geolocation"
Line : 2225

Final
![sonuc](https://cloud.githubusercontent.com/assets/7994408/25386486/33f5a346-29d0-11e7-8c06-b06278d4e2b9.PNG)

And it is probabby in your code [TypeScript.tmLanguage#L3537](https://github.com/Microsoft/TypeScript-TmLanguage/blob/master/TypeScript.tmLanguage#L3537)

**Comment by sheetalkamat** [comment]
@ugurozturk As I mentioned that's by design. All usage of variable named "Geolocation" are classified as dom class instead of just variable.
