### ISSUE TITLE
Incorrect Highlighting After Ternary Operator 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#451]
From https://github.com/Microsoft/vscode/issues/26273

**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.19 / latest

**Code**

```ts
function foo() {
    const filter = true ? (new RegExp('').test('123')) : () => true;
    return 123
}
```

**Bug**
![screen shot 2017-05-09 at 11 09 55 am](https://cloud.githubusercontent.com/assets/12821956/25865539/0e871738-34a8-11e7-9166-5530ffb6e817.png)

* `new RegExp` is not highlighted
* `return` is not highlighted
* This also leaks out of the function block so that later declarations are not properly highlighted:

![screen shot 2017-05-09 at 11 12 13 am](https://cloud.githubusercontent.com/assets/12821956/25865629/5e467782-34a8-11e7-8462-1010c6cea026.png)

**Comment by sheetalkamat** [comment]
This is by design. The limitation of being able to match anything with just regular expression and error recovery makes it hard to correctly detect if user meant it as type annotation or as ternary operator. 

There is work around for your issue here. You can write the arrow function on next line
![ternaryandarrow](https://cloud.githubusercontent.com/assets/8052792/26226322/826f82a4-3be0-11e7-8624-7fcc8dd11765.JPG)
