### ISSUE TITLE
type intersection without semicolon breaks scope for remainder of document

### ISSUE THREAD

**Issue by nfour** [Microsoft/TypeScript-TmLanguage#454]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.19 / latest

**Code**

```tsx
export type IProps = RouteComponentProps<any> & IStore

render(
  <Provider {...store}>
    <Router>
      <Route exact path='/' component={Board} />
    </Router>
  </Provider>,
  document.body.appendChild(document.createElement('div')),
)
```

Removing the semi as below breaks the scopes :-1: 

Here are some screenshots:

![Imgur](http://i.imgur.com/2hoU2K5.png)
![Imgur](http://i.imgur.com/ZII88bs.png)
![Imgur](http://i.imgur.com/uviYE4R.png)

**Comment by sheetalkamat** [comment]
This is by design as we expect most of the type declarations to follow by the other declaration or end with semicolon. We want to handle multiline type declaration and because tmLanguage can only lookup one line at a time and limits the error recovery, we have to let this be by design in favor of others because this .is the least common pattern we have seen so far
