### ISSUE TITLE
$ is highlighted as a keyword inside regexp

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/TypeScript-TmLanguage#505]
VS Code issue: https://github.com/Microsoft/vscode/issues/32951

Code:

```js
/abc$/
```

![image](https://user-images.githubusercontent.com/2193314/29581948-cf0cf9e4-872f-11e7-886a-a8a7a3cc0c2f.png)

**Comment by mjbvz** [comment]
@Tyriar I'm a fan of the current colorization since it helps distinguish parts of the regexp. Atom  out of the box also does this:

<img width="174" alt="screen shot 2017-08-22 at 3 38 02 pm" src="https://user-images.githubusercontent.com/12821956/29590698-f0bc6f0a-874f-11e7-8c4d-1ab55285c61e.png">

As does sublime: 

<img width="100" alt="screen shot 2017-08-22 at 3 39 13 pm" src="https://user-images.githubusercontent.com/12821956/29590725-1171ff8a-8750-11e7-8e2f-79c4e3790eab.png">

(although i'm not sure if they are all just using this grammar which could explain things)

**Comment by Peter-Juhasz** [comment]
I am sorry @mjbvz but I totally don't get your point.
1. Why would be a good idea to colorize only `$` characters as **keywords** in a regular expression literal? Why is this character so special? None of the other tokens are distinguished, for example `(`, `[`, `\A`, `+`, `.`, `?`, `{` ... so why is `$`? It is definitely a bug.
2. If you are using the same language service in Sublime then hopefully your language service works the same, this is not sublime that parses TypeScript/JavaScript in parallel and colorize random characters in regex literals as keywords.

**Comment by yume-chan** [comment]
@Peter-Juhasz Of course `$` is a keyword in regular expression, can you take just one minute to check the documentation before posting?

[Regular Expressions on MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions#Using_special_characters)

Character | Meaning
-- | --
$ | Matches end of input. If the multiline flag is set to true, also matches immediately before a line break character.For example, /t$/ does not match the 't' in "eater", but does match it in "eat".

**Comment by mjbvz** [comment]
1. Here's a quick example of what is currently colored:

<img width="505" alt="screen shot 2017-08-22 at 11 33 14 pm" src="https://user-images.githubusercontent.com/12821956/29601848-62e15aea-8792-11e7-905b-df6fc55e612b.png">

Quantifiers and special symbols (`$`, `^`, and `\b`) are generally colored. Group symbols are not. I'm in favor of adding more colors, not fewer. 

2. This is unrelated to the language service. Atom, Sublime, and Code all uses textmate grammars for syntax coloring but I don't know which versions of the JS/TS grammar each uses. We generally like to make sure that VS Code is somewhat consistent with the other editors out there for syntax coloring

**Comment by Peter-Juhasz** [comment]
Yes I did. Can you please read my post before posting something obvious?

![image](https://user-images.githubusercontent.com/9047283/29601733-50b77fca-87dd-11e7-9275-9b1409d09cd1.png)

And explain why `$` is treated as a keyword while any other tokens are not? You just linked a super long table which does not make any difference between `$` or `+`. They are different semantically but still don't see why should be one of them promoted as a keyword.

Character | Meaning
-- | --
$ | Matches end of input. If the multiline flag is set to true, also matches immediately before a line break character.      For example, /t$/ does not match the 't' in "eater", but does match it in "eat".
`*` | Matches the preceding expression 0 or more times. Equivalent to {0,}.      For example, /bo*/ matches 'boooo' in "A ghost booooed" and 'b' in "A bird warbled" but nothing in "A goat grunted".

**Comment by Peter-Juhasz** [comment]
Thanks, @mjbvz. It explains a few things.

**Comment by Peter-Juhasz** [comment]
Just to let you know guys the story behind this. I am a Visual Studio, .NET/C# user and when I first opened the same file in Visual Studio Code I saw that something is wrong here (Visual Studio uses the same style as C#). The literal was this: `/\.ts$/`. I remembered that in Visual Studio Code also string interpolation delimiters like `` `${1}` `` and lambda operators `=>` are classified as keywords (which are other weird things), so this might interfere with them. I would never thought `$` is considered as a keyword intentionally.

I did try some other meta characters but didn't tried character `^`, so I could see that there is some logic behind the colorization. Now I can see on the screenshot that some corresponding semantics are colorized the same.

Another counter argument I had in my mind was why would something like this be built into the TypeScript grammar itself instead of building an independent Regular Expression grammar and use projection buffers like Visual Studio does for embedded languages.

While I still don't see why some constructs of regular expressions are promoted to keywords, now I can see it is a feature.

**Comment by mjbvz** [comment]
Thanks for the background. After looking over how regular expressions are tokenized, I don't think this is an issue with the grammar. This grammar outputs all the necessary info about regular expression components, which individual themes can choose to colorize or not. Most of our builtin themes use the keyword coloring for special regexp characters such as `$`

I think this issue should be closed as by-design / up to individual themes

**Comment by Peter-Juhasz** [comment]
Yes, we can close this.
