### ISSUE TITLE
Javascript 'binding-pattern' TM scope

### ISSUE THREAD

**Issue by psxcode** [Microsoft/TypeScript-TmLanguage#614]
Please look at the following code samples
In first case, 'binding-pattern' scope was identified as expected
In second case, the scope is identified as 'objectliteral', which is not correct

**Code**

```js
// 'punctuation.definition.binding-pattern'
// properly identified
const func = ({ prop1, prop2 }) => {
   // code
}
```

```js
// identified as 'meta.objectliteral'
const func = ({ 
   prop1,
   prop2
}) => {
   // code
}
```

**Comment by sheetalkamat** [comment]
This  is because of limitation of tmLanguage syntax scopes where in we cant lookup beyond new line. On line ```const func = ({``` just looking at that we cant ensure whether its object literal or arrow and object literal is more safer pick. But we do handle this case specially trying to ensure types on next line can be colored better with PR #552 but thats the best we can do for now.

**Comment by karl** [comment]
That is great info, thanks @sheetalkamat

Has there been any discussion around expanding the tmLanguage syntax to allow it to look beyond one line?
