### ISSUE TITLE
async multiline arrow function is treated as a function call in expression

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#705]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  latest

**Code**

```ts
async (arg: string) => { }

async (
    asg: string
) => { }
```

In the second case, it looks like we are parsing it as a function call instead of a function declaration. 

Not sure if this is fixable or not given the complexities of multiline matches. Would it be somewhat safe  to assume that `async` + space + paren indicates the start of an arrow function? (I know that you could define a function called async and invoke it like `async  (myArgs)`)

**Comment by Foxhoundn** [comment]
It's not just with the `async` modifier. It breaks as long as there is a function inside a function call parameters.

<img width="684" alt="screenshot 2019-01-10 at 08 56 53" src="https://user-images.githubusercontent.com/8861481/50954150-de234400-14b5-11e9-8ada-d9ae62f1aa09.png">

Full code
```javascript
/* @flow */
import { createAction } from 'redux-actions';
import { fetchWithNotifications, post } from '../../utils';
import settings from '../../../../settings';

const authorizeClient: Function = createAction(
  'SYSTEM_AUTHORIZECLIENT',
  (
    requestData: Object,
    dispatch: Function
  ): void => {
    fetchWithNotifications(
      async () => {
        await post(
          `${settings.REST_BASE_URL}/oauth2/v1/code?type=code&clientId=${
            requestData.client_id
          }`
        );
      },
      `Authorizing client ${requestData.client_id}...`,
      `Client ${requestData.client_id} successfully authorized.`,
      dispatch
    );
  }
);

export { authorizeClient };
```

**Comment by sheetalkamat** [comment]
That part is intentional and limitation of tmLanguage syntax where in lookups are current line spanning only So we take conservative approach and apply expression like identifier rules and then if nothing then apply the type rules so this is best we can do. Eg. `just writing Function in js is `support.class.builtin` and so is it that way in this case. In most themes these are colored like other types and works as a great work around.

as @mjbvz mentioned `async(` can be function call and there was explicit issue for it and hence its intended to stay that way.

**Comment by Foxhoundn** [comment]
Ok but `async` is a reserved keyword already supported in all recent browsers, so why can't you treat it as one? 

And why can't values after `: ` like `: Function` outside of objects be treated as types?

Sorry but I feel like these "limitations" are not technological ones.

Thanks for your info.
